# Generated by Django 4.2.1 on 2023-05-16 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='email',
            name='user',
        ),
    ]
