# Generated by Django 4.2.1 on 2023-05-18 23:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_remove_email_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='builing_score_body',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='email',
            name='fakenews_score_body',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='phishing_score_body',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='email',
            name='phishing_score_header',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='url',
            name='email',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='emails.email'),
        ),
    ]
