# Generated by Django 4.2.1 on 2023-05-19 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_email_builing_score_body_email_fakenews_score_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='emailId',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
