# Generated by Django 4.2.1 on 2023-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0004_email_emailid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('emailId',)},
        ),
        migrations.AddField(
            model_name='email',
            name='from_email',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
