# Generated by Django 4.2.1 on 2023-05-19 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0005_alter_email_options_email_from_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='date',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AddField(
            model_name='email',
            name='subject',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
