# Generated by Django 4.2.1 on 2023-05-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0006_email_date_email_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='date',
            field=models.CharField(default='0', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='from_email',
            field=models.CharField(default='0', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='email',
            name='subject',
            field=models.CharField(default='0', max_length=256, null=True),
        ),
    ]
