# Generated by Django 4.2.1 on 2023-05-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0007_alter_email_date_alter_email_from_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='email',
            options={'ordering': ('-emailId',)},
        ),
        migrations.AlterField(
            model_name='email',
            name='builing_score_body',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='fakenews_score_body',
            field=models.FloatField(default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='phishing_score_body',
            field=models.CharField(default='0', max_length=256),
        ),
        migrations.AlterField(
            model_name='email',
            name='phishing_score_header',
            field=models.CharField(default='0', max_length=256),
        ),
    ]
